# Generated by Django 3.2.5 on 2021-07-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210722_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='bz_arti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harm', models.BooleanField(default=False)),
                ('clash', models.BooleanField(default=False)),
                ('horse', models.BooleanField(default=False)),
                ('peachb', models.BooleanField(default=False)),
                ('grave', models.BooleanField(default=False)),
                ('xing', models.BooleanField(default=False)),
                ('first', models.CharField(max_length=10, unique=True)),
                ('second', models.CharField(max_length=10, unique=True)),
                ('mean', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bz_bumi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karakter', models.CharField(max_length=10, unique=True)),
                ('pinyin', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('elemen', models.CharField(blank=True, max_length=10, null=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bz_health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemen', models.CharField(blank=True, max_length=10, null=True)),
                ('mean', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bz_kua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kua', models.CharField(max_length=10, unique=True)),
                ('hadap', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bz_langit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karakter', models.CharField(max_length=10, unique=True)),
                ('pinyin', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('elemen', models.CharField(blank=True, max_length=10, null=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bz_persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('birthdate', models.DateField()),
                ('birthhour', models.IntegerField()),
                ('kua', models.CharField(blank=True, max_length=10, null=True)),
                ('yya', models.CharField(max_length=10, unique=True)),
                ('yyb', models.CharField(max_length=10, unique=True)),
                ('mma', models.CharField(max_length=10, unique=True)),
                ('mmb', models.CharField(max_length=10, unique=True)),
                ('dda', models.CharField(max_length=10, unique=True)),
                ('ddb', models.CharField(max_length=10, unique=True)),
                ('hra', models.CharField(max_length=10, unique=True)),
                ('hrb', models.CharField(max_length=10, unique=True)),
                ('lucka1', models.CharField(max_length=10, unique=True)),
                ('luckb1', models.CharField(max_length=10, unique=True)),
                ('lucka2', models.CharField(max_length=10, unique=True)),
                ('luckb2', models.CharField(max_length=10, unique=True)),
                ('lucka3', models.CharField(max_length=10, unique=True)),
                ('luckb3', models.CharField(max_length=10, unique=True)),
                ('lucka4', models.CharField(max_length=10, unique=True)),
                ('luckb4', models.CharField(max_length=10, unique=True)),
                ('lucka5', models.CharField(max_length=10, unique=True)),
                ('luckb5', models.CharField(max_length=10, unique=True)),
                ('lucka6', models.CharField(max_length=10, unique=True)),
                ('luckb6', models.CharField(max_length=10, unique=True)),
                ('lucka7', models.CharField(max_length=10, unique=True)),
                ('luckb7', models.CharField(max_length=10, unique=True)),
                ('lucka8', models.CharField(max_length=10, unique=True)),
                ('luckb8', models.CharField(max_length=10, unique=True)),
                ('lucka9', models.CharField(max_length=10, unique=True)),
                ('luckb9', models.CharField(max_length=10, unique=True)),
                ('masfem', models.CharField(blank=True, max_length=10, null=True)),
                ('body', models.CharField(blank=True, max_length=10, null=True)),
                ('bone', models.CharField(blank=True, max_length=10, null=True)),
                ('yongshen', models.CharField(blank=True, max_length=10, null=True)),
                ('xishen', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bz_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm', models.CharField(max_length=10, unique=True)),
                ('month', models.CharField(max_length=10, unique=True)),
                ('story', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bz_annual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bz_langit')),
                ('second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bz_bumi')),
            ],
        ),
    ]
