# Generated by Django 3.2.5 on 2021-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bz_annual_bz_arti_bz_bumi_bz_health_bz_kua_bz_langit_bz_persona_bz_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='bz_story',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bz_arti',
            name='first',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bz_arti',
            name='second',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
