# Generated by Django 3.2.5 on 2021-07-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210724_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bz_bumi',
            old_name='desc',
            new_name='desc_neg',
        ),
        migrations.RenameField(
            model_name='bz_langit',
            old_name='desc',
            new_name='desc_neg',
        ),
        migrations.AddField(
            model_name='bz_bumi',
            name='desc_pos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bz_langit',
            name='desc_pos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
