# Generated by Django 3.2.5 on 2021-07-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210724_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bz_story',
            name='month',
        ),
        migrations.AddField(
            model_name='bz_story',
            name='season',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bz_story',
            name='too_much',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bz_story',
            name='dm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
