# Generated by Django 3.2.5 on 2021-07-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210724_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bz_story',
            old_name='season',
            new_name='tubuh',
        ),
        migrations.AddField(
            model_name='bz_story',
            name='yongshen',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bz_story',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
