# Generated by Django 3.2.5 on 2021-07-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210725_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bz_story',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
