# Generated by Django 3.2.5 on 2021-07-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_bz_story_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bz_health',
            name='kurangi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
